#
# Server Properties
#
server:
    ssl:
        enabled: true
        keyStore: ${user.home}/.keystore
        keyStorePassword: changeit
        protocol: ${SSL_PROTOCOL:TLSv1.2}
        ciphers: ${SSL_CIPHERS:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA}

#
# Management Properties
#
management:
    contextPath: /admin
    security:
        #
        # Enable security for management endpoints
        # 
        enabled: ${MANAGEMENT_SECURITY_ENABLED:true}
        #
        # Role required to view the Actuator endpoints
        # (defatuls to ACTUATOR in Spring Boot 1.5
        # 
        roles: ${MANAGEMENT_SECURITY_ROLES:ADMIN}
    #
    # Information Properties
    #
    info:
        #
        # The values below are bound to an instance of InfoContributorProperties
        #
        build:
            enabled: ${MANAGEMENT_INFO_BUILD_ENABLED:true}    # Enable build info.
        defaults:
            enabled: ${MANAGEMENT_INFO_DEFAULT_ENABLED:true}  # Enable default info contributors.
        env:
            enabled: ${MANAGEMENT_INFO_ENV_ENABLED:true}      # Enable environment info.
        git:
            enabled: ${MANAGEMENT_INFO_GIT_ENABLED:true}      # Enable git info.
            mode: ${MANAGEMENT_INFO_GIT_MODE:simple}          # Mode to use to expose git information (simple or full)

#
# Logging Properties
#
logging:
    level:
        org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:WARN}
        org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:WARN}
        org.springframework.security.oauth2: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_OAUTH2:WARN}
        org.springframework.boot: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT:WARN}
        org.springframework.boot.actuate: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_ACTUATE:WARN}
        org.springframework.cloud.config.client: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONFIG_CLIENT:WARN}
        org.springframework.cloud.config.server: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONFIG_SERVER:WARN}
        org.springframework.cloud.netflix: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_NETFLIX:WARN}
        com.netflix: ${LOGGING_LEVEL_COM.NETFLIX:DEBUG}
        sample: DEBUG

