#
# Test Properties
#
test:
    #
    # Authentication Properties
    #
    userUsername: ${TEST_USER_USERNAME:user}
    userPassword: ${TEST_USER_PASSWORD:user}
    adminUsername: ${TEST_ADMIN_USERNAME:admin}
    adminPassword: ${TEST_ADMIN_PASSWORD:admin}

